* Dvorak keyboard layout for the Catalan language

Following Dvorak's keyboard's layout philosophy, here you can an
implementation for the Catalan language. It's been my keyboard layout
since 2009 and I am very pleased with it.

In this repository you can find files to use Catalan Dvorak on
Debian-ish operating sistems.
** Files included
- =ct= :: XKeyboardConfig symbols file. This is the file to modify if you
        are not comfortable with some keys position and would like to
        fix them.
- =catvorak= :: bash program to set the catdvorak keyboard
                layout. Basically it runs =setxkbmap -layout ct=.
- =gb= :: bash program to set a standard Great Britain keyboard
          layout. Basically it runs =setxkbmap -layout gb=.
- =90-catdvorak-kbd.conf= :: X11 configuration file to autostart catdvorak.
- =freq_cat.ods= :: Visual of catdvorak layout, and comparison of hand &
                    finger use between Catdvorak and Qwerty layouts.
- =freq_cat.pdf= :: pdf export of =freq_cat.ods=
- =README.org= :: this file
- =LICENSE= :: GNU GPL3
** Installation
#+BEGIN_SRC
$> git clone https://github.com/gorgnegre/catdvorak.git
$> cd catdvorak
$> sudo mv ct /usr/share/X11/xkb/symbols/ct
$> sudo mv catdvorak gb /usr/local/bin
$> sudo mv 90-catdvorak-kbd.conf /etc/X11/xorg.conf.d/
#+END_SRC
** Use
If you want to use the catdvorak layout, run either
#+BEGIN_SRC
$> catdvorak
#+END_SRC
or
#+BEGIN_SRC
$>  setxkbmap -layout ct=
#+END_SRC.

To go back to a standard uk layout, run either
#+BEGIN_SRC
$> gb
#+END_SRC
or
#+BEGIN_SRC
$>  setxkbmap -layout gb=
#+END_SRC.

Check https://wiki.debian.org/Keyboard for other ways of setting the layout.
